### ISSUE TITLE
still trying to build it..

### ISSUE THREAD

**Issue by itapi** [smasherprog/Remote_Access_Library#1]
it downloaded so many things... it got to 4gb...

why so alot?

**Comment by smasherprog** [comment]
Will check this out when I get back from work today.

**Comment by smasherprog** [comment]
I was able to check this out really quick. All of the size comes from the boost nuget packages. If you check out the size of the packages directory, you will see its all of the different boost libs.
Let me know if you see the same thing.

**Comment by itapi** [comment]
@smasherprog  yeah youre right- by the way im trying to launch it now and this is the exceptions i get
![image](https://cloud.githubusercontent.com/assets/10478457/12486231/59e69fea-c06a-11e5-8f1c-e33aa5112c0b.png)


in the client & server too.

**Comment by smasherprog** [comment]
You are likely using VS 2013. I use 2015, so you need to set your platform toolset by highlighting all the projects and selecting here.
![capture](https://cloud.githubusercontent.com/assets/3393733/12500885/38620d8a-c06c-11e5-9662-492d7eb6b113.PNG)

**Comment by itapi** [comment]
@smasherprog allright changed the entire solution to v120(my version) and now im getting this.. 
![image](https://cloud.githubusercontent.com/assets/10478457/12506281/6414486e-c0f6-11e5-9a14-c5d47df451d4.png)

damn.  i really appreciate your help :) 
please suggest me what to do

**Comment by smasherprog** [comment]
https://github.com/smasherprog/Remote_Access_Library/wiki/Visual-Studio-Development

**Comment by smasherprog** [comment]
Closing this issue. Please open a new one if you have further questions

**Comment by itapi** [comment]
@smasherprog  waitt haha i just missed your last message,what did you mean by this link?
i mean how it should solve the errors? i did as you said before(setted it to v120) and now getting tons of other errors :) i would really like to try this project it's somthing i investigate and search about alot(in c#  unforunately,haha).
