### ISSUE TITLE
hey one last problem im facing with the build

### ISSUE THREAD

**Issue by itapi** [smasherprog/Remote_Access_Library#2]
when i  try to build i get this single error 
![image](https://cloud.githubusercontent.com/assets/10478457/13204850/b269add4-d8e2-11e5-81a2-6359d8dc7fc4.png)

searched for this file in my computer and couldnt find it too.
i'll appreciate every help .

thank you so much! :)

**Comment by smasherprog** [comment]
You need to install the libturbo-jpeg libraries
https://github.com/smasherprog/Remote_Access_Library/wiki/Visual-Studio-Development
You need to download and install both the 32 bit and 64 bit and install using the default locations. After that it will build successfully.

**Comment by smasherprog** [comment]
Closing this issue since I havent heard anything back on this.
