### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by k1rn1l** [smasherprog/Remote_Access_Library#42]
error	TS2095	Could not find symbol 'TouchEvent'.	Desktop_Server	D:\github\Remote_Access_Library\wwwroot\Core.ts	488	
error	TS2095	Could not find symbol 'TouchEvent'.	Desktop_Server	D:\github\Remote_Access_Library\wwwroot\Core.ts	494	
error	TS2095	Could not find symbol 'TouchEvent'.	Desktop_Server	D:\github\Remote_Access_Library\wwwroot\Core.ts	501	
error	TS2095	Could not find symbol 'TouchEvent'.	Desktop_Server	D:\github\Remote_Access_Library\wwwroot\Core.ts	523	
error	TS2094	The property 'slice' does not exist on value of type 'ArrayBuffer'.	Desktop_Server	D:\github\Remote_Access_Library\wwwroot\Core.ts	769	
error	TS2094	The property 'slice' does not exist on value of type 'Uint8Array'.	Desktop_Server	D:\github\Remote_Access_Library\wwwroot\Core.ts	13

**Comment by smasherprog** [comment]
Make sure you are running the latest version of typescript

open a command prompt and type tsc --version

It should report version 1.8.10. If it doesnt, you can update it here 
https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/1.8.11

**Comment by smasherprog** [comment]
Actually Forget the above comment, 

Just update your npm package


open a command prompt and type  

npm install tsc -g

Then, Close visual studio, reopen it and try to recompile the typescript. It should work.
I am very close to releasing a large codebase change and Ill get this fixed as well so it all should just " work"

**Comment by k1rn1l** [comment]
I tried the above two methods, but the problem is not solved.
---------------------------------------------------------------------------
C:\Users\k1rn1l>npm install tsc -g
C:\Users\k1rn1l\AppData\Roaming\npm\tsserver -> C:\Users\k1rn1l\AppData\Roaming\
npm\node_modules\tsc\bin\tsserver
C:\Users\k1rn1l\AppData\Roaming\npm\tsc -> C:\Users\k1rn1l\AppData\Roaming\npm\n
ode_modules\tsc\bin\tsc
C:\Users\k1rn1l\AppData\Roaming\npm
`-- tsc@1.20150623.0
C:\Users\k1rn1l>tsc --version
Version 1.0.3.0

I closed visual studio, reopen it and try to recompile the project.
But the error still exists.
--------------------------------------------------------------------------
I try to another solution:
run the following command in the Package Manager Console
PM > Install-Package Microsoft.TypeScript.MSBuild
--------------------------------------------------------------------------
Then, I closed visual studio, reopen it and try to recompile the project.
But the error still exists.

**Comment by smasherprog** [comment]
You have an old version of tsc installed on your computer.
Probably an early version from visual studio.

Are you building against Dev or Release build?>

**Comment by k1rn1l** [comment]
Changing the system environment variables:
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\
--> C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\
Compiler success.
Thank you for your enthusiastic help. :D

**Comment by smasherprog** [comment]
you could install this
https://www.microsoft.com/en-us/download/details.aspx?id=48593
But that wouldnt fix the problem because you have an old version of tsc in your system path. You need to update your system path to remove this old version of typescript from your path. It will then use your tsc installed from npm.

In the next release -- within the next week-- I am going to fix this by using the node package ntypescript.

**Comment by smasherprog** [comment]
Ahh glad to hear!

**Comment by smasherprog** [comment]
I went through a similar experience. Its strange that for initial installs the system path is updated, but when you install new ones, the old system path is not modified.... Very annoying
