### ISSUE TITLE
Do they support a multi user view of the same server desktop?

### ISSUE THREAD

**Issue by tensafe** [smasherprog/Remote_Access_Library#58]
Do It support multi users view same server desktop?
like this:
Https://blogs.msdn.microsoft.com/rds/2007/03/23/writing-a-desktop-sharing-application/

**Comment by smasherprog** [comment]
Yes, multiple users can view and control the same server.

As far as this project goes, its under major reworking on the dev branch currently.  I am trying to streamline my dependencies.
