### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [smasherprog/Remote_Access_Library#59]
I would like to point out that identifiers like “[`_ClipboardImpl`](https://github.com/smasherprog/Remote_Access_Library/blob/4e0db20dea973ffb86e7ba9086ebe8cf0164e26c/Core/Clipboard.h#L9 "Update candidate")” and “[`_LogWindowImpl`](https://github.com/smasherprog/Remote_Access_Library/blob/c8854ad38c1ba47c8fdb662aceb96156bc79111d/Core/LogWindow.h#L9 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by smasherprog** [comment]
You are absolutely right. I am working on removing all of these names and also prepping for a large update to the code base. This will be within the next few weeks

**Comment by smasherprog** [comment]
Went through the codebase and removed all of these names. 
Fixed in Commit https://github.com/smasherprog/Remote_Access_Library/commit/bb5125f49634670c3a5c1b4129f865bbdea5cc06

**Comment by elfring** [comment]
Thanks for [your improvement of affected identifiers](https://github.com/smasherprog/Remote_Access_Library/commit/bb5125f49634670c3a5c1b4129f865bbdea5cc06 "Renaming of some identifiers").
